# AEROSPACE CONFIG
# https://github.com/edunfelt/base16-rose-pine-scheme/blob/main/assets/palette.png
start-at-login = true

after-login-command = []

after-startup-command = [
    # 'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color=0xFFFFBE69 inactive_color=0xFF007692 width=8.0',
    # 'exec-and-forget brew services start sketchybar'
]

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
  'exec-and-forget sketchybar --trigger send_message MESSAGE="WORKSPACE CHANGED"',
]

# on-focused-monitor-changed = [
#   'move-mouse monitor-lazy-center'
# ]

on-focus-changed = [
  # 'move-mouse window-lazy-center',
  'exec-and-forget /bin/bash -c /opt/homebrew/bin/sketchybar --trigger front_app_switched',
  'exec-and-forget sketchybar --trigger update_windows'
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    outer.top =        [{ monitor."built-in.*" = 26 }, 60]
    outer.bottom =     [{ monitor."built-in.*" = 10 }, 12]
    inner.horizontal = [{ monitor."built-in.*" = 10 }, 12]
    inner.vertical =   [{ monitor."built-in.*" = 10 }, 12]
    outer.left =       [{ monitor."built-in.*" = 10 }, 12]
    outer.right =      [{ monitor."built-in.*" = 10 }, 12]

[exec]                   # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true  # If you don't touch "exec" section,
[exec.env-vars]          # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                   sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift
[mode.main.binding]

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # alt-enter = '''exec-and-forget open -n -a "Warp" --args --new-window --command "fastfetch"'''

    alt-space = 'layout floating tiling'

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    # alt-0 = 'workspace 0'
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    # alt-a = 'workspace A'
    # alt-b = 'workspace B'
    # alt-c = 'workspace C'
    # alt-d = 'workspace D'
    # alt-e = 'workspace E'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    # alt-shift-0 = 'move-node-to-workspace 0'
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    # alt-shift-a = 'move-node-to-workspace A'
    # alt-shift-b = 'move-node-to-workspace B'
    # alt-shift-c = 'move-node-to-workspace C'
    # alt-shift-d = 'move-node-to-workspace D'
    # alt-shift-e = 'move-node-to-workspace E'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-shift-s = [
        'mode service',
        'exec-and-forget sketchybar --trigger send_message MESSAGE="SERVICE MODE" HOLD="true"'
    ]

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = [
        'reload-config',
        'exec-and-forget sketchybar --trigger hide_message',
        'exec-and-forget sketchybar --reload',
        'mode main'
    ]
    r = ['flatten-workspace-tree', 'mode main'] # reset layout

    s = [
        'exec-and-forget cat ~/.config/aerospace/shrugstring| pbcopy',
    'exec-and-forget sketchybar --trigger hide_message',
    'mode main'
    ] 

    b = [
    'exec-and-forget ~/.config/aerospace/presentation.sh on',
    'exec-and-forget sketchybar --bar height=0',
    'exec-and-forget sketchybar --trigger hide_message',
    'mode main'
    ]

    shift-b = [
    'exec-and-forget ~/.config/aerospace/presentation.sh off',
    'exec-and-forget sketchybar --bar height=36',
    'exec-and-forget sketchybar --trigger hide_message',
    'mode main'
    ]

    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']

# Finder
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['move-node-to-workspace 1']

# Zen
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = ['layout tiling', 'move-node-to-workspace 2']

# VSCode
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['layout tiling', 'move-node-to-workspace 3']

# Warp
[[on-window-detected]]
if.app-id = 'dev.warp.Warp-Stable'
run = ['layout tiling', 'move-node-to-workspace 4']

# WhatsApp
[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = ['layout floating', 'move-node-to-workspace 5']

# Spotify
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['layout floating', 'move-node-to-workspace 6']

# Obsidian
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout tiling', 'move-node-to-workspace 7']

# Todoist
[[on-window-detected]]
if.app-id = 'com.todoist.mac.Todoist'
run = ['layout tiling', 'move-node-to-workspace 7']

# Preview
[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = ['layout floating', 'move-node-to-workspace 9']

# System Settings
[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['layout floating', 'move-node-to-workspace 9']